spring:
  application:
    name: service-gateway
server: 
  port: 8080
zuul:
  ignoredServices: '*'
  routes:
    app:
      path: /app/**
      stripPrefix: true
      serviceId: app-service
    foos:
      path: /spring-zuul-foos-resource/foos/**
      stripPrefix: false
      serviceId: resource-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka/

