eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka/
    fetchRegistry: true
server:
  port: 8080
spring:
  application:
    name: service-gateway
zuul:
  routes:
    app:
      path: /app/**
      url: http://localhost:18080
    foos:
      path: /foos/**
      url: http://localhost:18082/foos
      #url: http://localhost:18082/spring-zuul-foos-resource/foos
      #serviceID: API-SERVICE
      #servicePath: /spring-zuul-foos-resource/foos
      stripPrefix: false
#ribbon:
  #eureka:
    #enabled: true