spring:
  application:
    name: service-gateway
server: 
  port: 8080
zuul:
  routes:
    app:
      path: /app/**
      url: http://localhost:18080
    foos:
      path: /spring-zuul-foos-resource/foos/**
      stripPrefix: false
      serviceId: resource-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka/

