spring:
  application:
    name: app-service
zuul:
  routes:
    foos:
      path: /foos/**
      url: http://localhost:18082/foos
      #url: http://localhost:18082/spring-zuul-foos-resource/foos
      #serviceId: api-service
server:
  port: 18080
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl: 
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka/
    #healthcheck:
      #enabled: true
    lease:
      duration: 5
    #instance:
      #preferIpAddress: true
      
